name: workflow_4

on: 
  push:
    branches:
      [release/**]

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout commit
        uses: actions/checkout@v2
   
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
        
      - name: Tests Unitarios
        run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.BookServiceUnitaryTest' test 
    
      - name: Tests Selenium
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.RestTest' test 