name: workflow_3

on: 
  schedule:
    - con: 0 0 * * *

  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout commit
        uses: actions/checkout@v2
        with: 
          ref: develop
   
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
        
      - name: Dskip Tests
        run: mvn -B package -DskipTests

      - name: Tests Unitarios
        run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.BookServiceUnitaryTest' test 
    
      - name: Tests Rest
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.RestTest' test 

      - name: Tests Selenium
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.selenium.SeleniumTest' test  

      - name: Upload jar for next job
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target
          retention-days: 1

  publish_in_dockerhub:

    name: Publish in DockerHub
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download Jar from previous job
        uses: actions/download-artifact@v2
        with:
        name: target

      - name: Generate tag
        run: echo ::set-output name=tag::$(date +'%Y%m%d.%H%M%S')
        id: project

      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/items:dev-${{ steps.project.outputs.tag }} .

      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/items:dev-${{ steps.project.outputs.tag }}
